# Generated by Django 5.2.8 on 2025-11-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='izucheno',
            field=models.IntegerField(blank=True, null=True, verbose_name='Изучено'),
        ),
    ]
