# Generated by Django 5.2.8 on 2025-11-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_words_izucheno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='izucheno',
        ),
        migrations.AddField(
            model_name='words',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Изучено'),
        ),
    ]
