# Generated by Django 5.2.8 on 2025-11-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_words_izucheno_words_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Изучено'),
        ),
    ]
