# Generated by Django 5.2.8 on 2025-11-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_note_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note',
            field=models.TextField(default=0, verbose_name='Заметка'),
            preserve_default=False,
        ),
    ]
