# Generated by Django 5.2.8 on 2025-11-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_note_note'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='words',
            unique_together={('slovo', 'perevod')},
        ),
    ]
