# Generated by Django 5.2.8 on 2025-11-28 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_words_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='word_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.words', verbose_name='Пара слов'),
        ),
    ]
