# Generated by Django 5.2.8 on 2025-11-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_note_word_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='word_id',
            new_name='word',
        ),
    ]
