# Generated by Django 5.2.8 on 2025-12-02 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_word_id_note_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zametki', to='core.words', verbose_name='Пара слов'),
        ),
    ]
