# Generated by Django 5.2.8 on 2025-12-19 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_note_word'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='профиль пользователя'),
            preserve_default=False,
        ),
    ]
