# Generated by Django 5.2.8 on 2025-12-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_words_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=200, verbose_name='Кодовое название')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
    ]
