# Generated by Django 5.2.8 on 2025-12-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_likescounter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likescounter',
            options={'verbose_name': 'Счетчик спасибок', 'verbose_name_plural': 'Счетчики спасибок'},
        ),
        migrations.RenameField(
            model_name='likescounter',
            old_name='count',
            new_name='likes',
        ),
    ]
